# Generated by Django 4.1.5 on 2023-02-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
